// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ggcmjbimtxiaaproarau.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdnY21qYmltdHhpYWFwcm9hcmF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2ODc1NzUsImV4cCI6MjA2NjI2MzU3NX0.0DUoAgDlFo6SxjOfV_IFkkZ273EYYTmoSmm9A22wV3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);